root: true
extends:
  - remcohaszing
rules:
  import/extensions: off
  import/no-extraneous-dependencies: off
  import/no-unresolved: off

  n/no-extraneous-import: off

  jsdoc/check-indentation: off
